version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 "app:app"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://makeja_user:makeja_pass@db/makeja_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=makeja_user
      - POSTGRES_PASSWORD=makeja_pass
      - POSTGRES_DB=makeja_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U makeja_user -d makeja_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
